### ISSUE TITLE
我跑通了您的代码，但是我没有搜到您论文的链接，可以分享您论文的题目和链接吗？

### ISSUE THREAD

**Issue by lian666-ch** [khanhha/crack_segmentation#9]

**Comment by noioion** [comment]
你好，你找到论文了吗，我也想阅读一下

**Comment by xiaomi576** [comment]
你好，我在运行代码的时候遇到了这样的问题，请问您知道如何处理吗？
Restored model at epoch 10. Min validation loss so far is : 0
Started training model from epoch 11

**Comment by noioion** [comment]
这是来自姚皓东QQ邮箱的自动回复邮件。你好，皓东已经收到你的邮件啦~会尽快下载查看的，辛苦啦~

**Comment by lian666-ch** [comment]
> _No description provided._



> _No description provided._
